project:
  type: website

website:
  title: "comunica"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: demo.qmd
        text: Grandes Números
      - href: abour.qmd
        text: Acerca de


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-block-border-left: "darkorange"
    code-block-bg: true
    fig-align: left


editor: visual

